name: contributor-takes-action
description: This is an action to assign yourself to an issue for a repo you are not a contributor to.
author: Brian Douglas
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  message:
    description: 'Message to prospective contributor'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    -
      run: |
        BODY="$(jq '.comment.body' $GITHUB_EVENT_PATH)"
        ISSUE_NUMBER="$(jq '.issue.number' $GITHUB_EVENT_PATH)"
        LOGIN="$(jq '.comment.user.login' $GITHUB_EVENT_PATH | tr -d \")"
        REPO="$(jq '.repository.full_name' $GITHUB_EVENT_PATH | tr -d \")"
        ISSUE_JSON="$(jq '.issue' $GITHUB_EVENT_PATH)"
        IS_USER_ASSIGNED=`echo $ISSUE_JSON | jq '.assignees | length == 0'`

        if [[ "$IS_USER_ASSIGNED" == false ]]; then
          echo $IS_USER_ASSIGNED
        fi
        if [[ "$IS_USER_ASSIGNED" == true  ]]; then
            echo $ISSUE_NUMBER
        fi
      shell: bash
      env:
        INPUT_MESSAGE: "${{ inputs.message }}"
